// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package openapi

import (
	"encoding/json"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// SignUpUser defines model for SignUpUser.
type SignUpUser struct {
	Email             string `json:"email"`
	EmailConfirmation string `json:"emailConfirmation"`
	Password          string `json:"password"`
	Username          string `json:"username"`
}

// DispatchJSONBody defines parameters for Dispatch.
type DispatchJSONBody struct {
	union json.RawMessage
}

// DispatchJSONRequestBody defines body for Dispatch for application/json ContentType.
type DispatchJSONRequestBody DispatchJSONBody
